name: deploy-vue-app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.3.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          remote-user: ${{ secrets.REMOTE_USER }}
          remote-host: ${{ secrets.REMOTE_HOST }}
          remote-port: ${{ secrets.REMOTE_PORT }}
          local-folder: dist/
          remote-folder: /var/www/html/
